# SPDX-FileCopyrightText: The uwuAOSP Project
# SPDX-License-Identifier: Apache-2.0
# This is an EXAMPLE, not a diting adaptation. Replace and review all services.
# Install as /system/etc/recovery.crypto.conf in the Recovery ramdisk only.
profile_version=1
platform_sdk=37
storage_binding=none
fstab=/system/etc/recovery.crypto.fstab
keymint_service=android.hardware.security.keymint.IKeyMintDevice/default
security_level=tee
gatekeeper_transport=aidl
gatekeeper_instance=default
weaver_transport=none
weaver_instance=
secureclock_service=
sharedsecret_services=android.hardware.security.sharedsecret.ISharedSecret/default
